# Generated by Django 5.0.4 on 2024-05-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nick',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
