# Generated by Django 5.0.4 on 2024-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contact_profile_contact_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='contact', to='users.contact'),
        ),
    ]
