# Generated by Django 5.0.4 on 2024-05-05 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_users_email_remove_users_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('about', models.CharField(max_length=500)),
                ('contacts', models.ManyToManyField(related_name='contact', to='chat.contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
        ),
    ]
