# Generated by Django 5.0.4 on 2024-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(null=True, related_name='contact', to='chat.contact'),
        ),
    ]
